name: Deploy

on:
  workflow_dispatch:
jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: estuba.sk
          username: htpt2.estuba.sk
          password: ${{ secrets.FTP_PASS }}